version: '3'
services:
  #
  #
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${DATA_FOLDER}/mosquitto/data:/mosquitto/data
      - ${DATA_FOLDER}/mosquitto/logs:/mosquitto/logs
      - ${CONFIG_FOLDER}/mosquitto:/mosquitto/config
    #user: "${UID}:${GID}"
    restart: unless-stopped
  #
  #
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    volumes:
      - ${DATA_FOLDER}/zigbee2mqtt/data:/app/data
      #- /run/udev:/run/udev:ro
    ports:
      - 8080:8080   # Frontend port
    restart: unless-stopped
    #network_mode: host
    #privileged: true
    environment:
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=zigbee2mqtt
      #- ZIGBEE2MQTT_CONFIG_MQTT_USER=
      #- ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto:1883
      - ZIGBEE2MQTT_CONFIG_MQTT_CLIENT_ID=z2mqtt
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=tcp://10.12.1.8:8888
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ezsp
      #- ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE=57600
      - ZIGBEE2MQTT_CONFIG_PERMIT_JOIN=false
      - ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL=debug
      - TZ=Europe/Zurich
    depends_on:
      - mosquitto