version: '3'
services:
  #
  #
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${DATA_FOLDER}/mosquitto/data:/mosquitto/data
      - ${DATA_FOLDER}/mosquitto/logs:/mosquitto/logs
      - ${CONFIG_FOLDER}/mosquitto:/mosquitto/config
    #user: "${UID}:${GID}"
    restart: unless-stopped
  #
  #
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    restart: always
    network_mode: host
    #privileged: true
    environment:
      - TZ=Europe/Zurich
  #
  #
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
